### ISSUE TITLE
[feature request] Create custom validator

### ISSUE THREAD

**Issue by eh-am** [AnthonyNahas/ngx-material-password-strength#38]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality
In my case I want the form to be invalid until user inputs a password with strength = 100.

I have two alternatives in mind:
create a custom validator using same REGEXes

Or something like this:
```
  onStrengthChanged($event) {
    if ($event < 100) {
      this.form.get('password').setErrors({ 'strength': true });
    }
  }
```

But of course, having the lib to provide a Validator would be better.

What do you think?

**Comment by AnthonyNahas** [comment]
hey @eh-am, I think this feature could be really interesting for some developers!
In my [ngx-auth-firebase](https://www.npmjs.com/package/ngx-auth-firebaseui) module (which has dependency to [ngx-material-password-strength](https://github.com/AnthonyNahas/ngx-material-password-strength) ), the password is validated on the server side via firebase... 
Client Side password validation should be optional too! That's why, I believe that providing an internal validator in this project is a good idea 👍 

### Disadvantage
- peer dependency to @angular/forms (I don't think that this would be a problem...)

Give me some days to improve that 🔨 

which version are you using ?

**Comment by eh-am** [comment]
Cool! I am using `"ngx-material-password-strength": "^2.0.0"`, let me know if you need any help!

**Comment by AnthonyNahas** [comment]
@eh-am I've just released `ngx-material-password-strength` **v2.1.0** which contains the requested feature!

![demo_with_validation](https://user-images.githubusercontent.com/20149774/40626467-fef3a9c2-62b8-11e8-98c4-821e770fe4ea.gif)

I added a built form controller in order to bind it to a user input like the following --> 

```html
<div>
  <mat-form-field appearance="outline" style="width: 100%">
    <mat-label>Password</mat-label>
    <input matInput #passwordWithValidation
           [type]="inputType"
           required
           [formControl]="passwordComponentWithValidation.passwordFormControl"
           placeholder="Password">
    <mat-hint align="end" aria-live="polite">
      {{passwordWithValidation.value.length}} / 25
    </mat-hint>
    <mat-error *ngIf="passwordComponentWithValidation.passwordFormControl.hasError('required')">
      Password is required
    </mat-error>
    <mat-error *ngIf="passwordComponentWithValidation.passwordFormControl.hasError('pattern')">
      Password is not valid
    </mat-error>
  </mat-form-field>
  <ngx-material-password-strength #passwordComponentWithValidation
                                  (onStrengthChanged)="onStrengthChanged($event)"
                                  [password]="passwordWithValidation.value">
  </ngx-material-password-
  <!--Password's strength info-->
  <ngx-material-password-strength-info
    [passwordComponent]="passwordComponentWithValidation">
  </ngx-material-password-stren
</div>
```

please take a look at the 
1. [readme](https://github.com/AnthonyNahas/ngx-material-password-strength)
2. [documentation](https://anthonynahas.github.io/ngx-material-password-strength/doc/index.html)
3. [demo app](https://anthonynahas.github.io/ngx-material-password-strength)

Thanks for requesting the great feature 💯

**Comment by SureshPonkam** [comment]
do we have form control for confirm password also? because when we want to validate the password and confirmpassword , its difficult to get form controls name as it is same for both .

**Comment by AnthonyNahas** [comment]
@SureshPonkam I see! May you open an appropriate issue for that ?
That would be the next feature of this library ! cheers 🍻

**Comment by rkimaoui** [comment]
+1 for confirmpassword support
